### ISSUE TITLE
Writing documentation

### ISSUE THREAD

**Issue by nathan-rabet** [DaemonOnUnix/Raccoon-exok#6]
# Where is the documentation ?

The project is interesting, but without documentation, it's **hard to contribute**.

## Suggestions (_necessary_)

In order to guide new contributors, it seems necessary to :

- Create a `README.md` (or another Markdown file) which explains all the project organisation + current features.

> For me, a good example is the README of the [Removed Private Publicity](https://github.com/dear-github/dear-github/issues/293) project. Because it explains what was done, what are the features and what is the project architecture.

- Explain how your kernel is initialized.

> You need to tell how your project is running => _bootloader start here, then the functions defined in the file `xxx.h` are called for that and that in the initialization of XXX, etc..._.

- Writing a summary in all the header files to explain what the following functions are used for.
- Writing documentation on each function definition.

> For me, an example of a good header documentation is in [include/net/netfilter](https://elixir.bootlin.com/linux/latest/source/include/net/netfilter/nf_conntrack.h) in the Linux kernel.
>> For single function definition, [Doxygen](https://fr.wikipedia.org/wiki/Doxygen) seems to be a good documentation tool.

## Suggestions (_optional_)

Also, if you don't want to lose time when someone create a PR, you can **create a coding style**.

> By coding style I include formatting **and** file organisation.

**Comment by DaemonOnUnix** [comment]
Hi,

I noted this. There are two facts you should consider. First, it isn't a kernel in a traditional sense, and then, specification is being done in private groups. This is a very strange kind of kernel and things are moving quickly.

Then, contributions are mostly awaited in LibOSes, the actual goal for the kernel being a pki creation.

You can do what you want in the LibOS. Kernel shouldn't be touched by any contribution. It will be stabilized by the end of the summer.

You can also look at the conference replay to understand what happens an what are the goals, and the code is really little and understandable. Including non osdev contributors told me that.

Regards,

Daniel
